### ISSUE TITLE
Iron Bars

### ISSUE THREAD

**Issue by TheWanderingTrader** [NemoNotFound/NemosMossyBlocks#3]
Iron bars are unable to be crafted as mossy iron bars and normal iron bars have the same recipe?

**Comment by NemoNotFound** [comment]
How are you trying to craft mossy iron bars? They can be crafted and don't have the same recipe as the iron bars. They have the same recipe as other moss recipes. Block + moss block/vines

**Comment by TheWanderingTrader** [comment]
<img width="599" alt="Screenshot 2024-06-09 at 11 09 32" src="https://github.com/NemoNotFound/NemosMossyBlocks/assets/168755675/2dba4646-e6cc-4ef5-904f-81d7ac1e1498">
<img width="589" alt="Screenshot 2024-06-09 at 11 09 23" src="https://github.com/NemoNotFound/NemosMossyBlocks/assets/168755675/64f9868a-e2e3-4c9e-b8c9-5738e40e3153">

**Comment by NemoNotFound** [comment]
On which version are you playing? On the latest version I don't have this

**Comment by NemoNotFound** [comment]
Oh wait huh. I do. Where does this come from

**Comment by NemoNotFound** [comment]
Oh I found it, oops. I accidentally added two recipes for that. WIll fix it immediately

**Comment by TheWanderingTrader** [comment]
Thank you!  Do you also have plans to have support for JEI/REI?

**Comment by NemoNotFound** [comment]
No problem! Thanks for pointing it out :D
Plans no, but I can take a look on how to do it

**Comment by TheWanderingTrader** [comment]
Of course and awesome sounds great :D

**Comment by NemoNotFound** [comment]
This issue is fixed with v1.4.2, it is currently uploading

**Comment by NemoNotFound** [comment]
It is uploaded now, so I'll close this ticket. I'll also add taking a look into jei to my tasks  :D
